#pragma once

// from glfw3.h
#define WG_MOUSE_BUTTON_1 0
#define WG_MOUSE_BUTTON_2 1
#define WG_MOUSE_BUTTON_3 2
#define WG_MOUSE_BUTTON_4 3
#define WG_MOUSE_BUTTON_5 4
#define WG_MOUSE_BUTTON_6 5
#define WG_MOUSE_BUTTON_7 6
#define WG_MOUSE_BUTTON_8 7
#define WG_MOUSE_BUTTON_LAST WG_MOUSE_BUTTON_8
#define WG_MOUSE_BUTTON_LEFT WG_MOUSE_BUTTON_1
#define WG_MOUSE_BUTTON_RIGHT WG_MOUSE_BUTTON_2
#define WG_MOUSE_BUTTON_MIDDLE WG_MOUSE_BUTTON_3